import { FighterConfig, FighterState, MoveType } from '../types/game';

export const FIGHTER_BOB: FighterConfig = {
  id: 'fighter_bob',
  name: 'Beefy Bob',
  subtitle: 'The Slipper Heavyweight Champion',
  stats: {
    maxHealth: 1000,
    walkSpeed: 0.082,
    dashSpeed: 0.175,
    jumpForce: 0.28,
    powerMultiplier: 1.15,
    weight: 1.15,
  },
  appearance: {
    primaryColor: 0xef4444, // Red boxing shorts & gloves
    secondaryColor: 0xf8fafc, // White trim
    skinColor: 0xfbbf24, // Warm cartoon skin
    gloveColor: 0xdc2626, // Bright red gloves
    hairColor: 0x78350f, // Brown
    eyeColor: 0x1e293b,
    bodyType: 'heavy',
    headShape: 'square',
    eyebrows: 'thick',
    mouth: 'grin',
    noseShape: 'broad',
    noseSize: 'large',
    hairStyle: 'headband',
    beard: 'stubble',
    shirtType: 'bare_chest',
    pantsType: 'shorts',
    pantsColor: 0xef4444,
    shoesType: 'boxing_boots',
    shoesColor: 0xf8fafc,
    gloveType: 'boxing_gloves',
    accessory: 'boxing_belt',
    specialItem: 'boxing_belt',
  },
  victoryQuote: 'Nobody can withstand the mighty Bicep of Justice!',
  defeatQuote: 'Ouch... my delicate chin...',
  koAnimation: {
    type: 'default_stars',
  },
  moves: {
    LIGHT_PUNCH: {
      name: 'Quick Jab',
      type: 'LIGHT_PUNCH',
      startupFrames: 4,
      activeFrames: 4,
      recoveryFrames: 6,
      totalFrames: 14,
      damage: 31,
      meterGain: 8,
      animType: 'lp',
      hitboxes: [
        {
          startFrame: 4,
          duration: 4,
          offsetX: 0.95,
          offsetY: 1.45,
          width: 0.65,
          height: 0.55,
          damage: 31,
          knockbackX: 0.09,
          knockbackY: 0.03,
          hitstun: 12,
          blockstun: 7,
          isHeavy: false,
          humorText: 'BOP!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_PUNCH: {
      name: 'Mega Haymaker',
      type: 'HEAVY_PUNCH',
      startupFrames: 10,
      activeFrames: 6,
      recoveryFrames: 16,
      totalFrames: 32,
      damage: 85,
      meterGain: 18,
      isHeavy: true,
      animType: 'hp',
      hitboxes: [
        {
          startFrame: 10,
          duration: 6,
          offsetX: 1.2,
          offsetY: 1.4,
          width: 0.9,
          height: 0.8,
          damage: 85,
          knockbackX: 0.28,
          knockbackY: 0.16,
          hitstun: 24,
          blockstun: 14,
          isHeavy: true,
          humorText: 'BONK!',
          soundType: 'heavy',
        },
      ],
    },
    LIGHT_KICK: {
      name: 'Shin Punt',
      type: 'LIGHT_KICK',
      startupFrames: 5,
      activeFrames: 4,
      recoveryFrames: 8,
      totalFrames: 17,
      damage: 36,
      meterGain: 10,
      animType: 'lk',
      hitboxes: [
        {
          startFrame: 5,
          duration: 4,
          offsetX: 1.0,
          offsetY: 0.45,
          width: 0.7,
          height: 0.55,
          damage: 36,
          knockbackX: 0.1,
          knockbackY: 0.02,
          hitstun: 14,
          blockstun: 8,
          isHeavy: false,
          humorText: 'POW!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_KICK: {
      name: 'The Yeet Kick',
      type: 'HEAVY_KICK',
      startupFrames: 12,
      activeFrames: 7,
      recoveryFrames: 18,
      totalFrames: 37,
      damage: 94,
      meterGain: 22,
      isHeavy: true,
      animType: 'hk',
      hitboxes: [
        {
          startFrame: 12,
          duration: 7,
          offsetX: 1.35,
          offsetY: 1.15,
          width: 0.95,
          height: 0.8,
          damage: 94,
          knockbackX: 0.35,
          knockbackY: 0.22,
          hitstun: 26,
          blockstun: 15,
          isHeavy: true,
          humorText: 'YEET!',
          soundType: 'heavy',
        },
      ],
    },
    SUPER_MOVE: {
      name: 'Tornado Bonk Barrage',
      type: 'SUPER_MOVE',
      startupFrames: 10,
      activeFrames: 34,
      recoveryFrames: 20,
      totalFrames: 64,
      damage: 221,
      meterGain: 0,
      superCost: 100,
      isSuper: true,
      isHeavy: true,
      animType: 'super',
      hitboxes: [
        {
          startFrame: 10,
          duration: 10,
          offsetX: 1.1,
          offsetY: 1.4,
          width: 0.9,
          height: 0.8,
          damage: 52,
          knockbackX: 0.12,
          knockbackY: 0.08,
          hitstun: 18,
          blockstun: 12,
          isHeavy: true,
          humorText: 'WHAM!',
          soundType: 'heavy',
        },
        {
          startFrame: 20,
          duration: 10,
          offsetX: 1.25,
          offsetY: 1.45,
          width: 1.0,
          height: 0.9,
          damage: 59,
          knockbackX: 0.14,
          knockbackY: 0.1,
          hitstun: 20,
          blockstun: 14,
          isHeavy: true,
          humorText: 'KAPOW!',
          soundType: 'heavy',
        },
        {
          startFrame: 30,
          duration: 14,
          offsetX: 1.5,
          offsetY: 1.6,
          width: 1.3,
          height: 1.2,
          damage: 110,
          knockbackX: 0.5,
          knockbackY: 0.38,
          hitstun: 35,
          blockstun: 20,
          isHeavy: true,
          humorText: 'GIGA BONK!!',
          soundType: 'super',
        },
      ],
    },
  },
  specials: [
    {
      id: 'bob_boulder_punch',
      name: 'Bicep Boulder Punch',
      command: 'QCF',
      button: 'HP',
      commandDisplay: '↓ → + HP',
      description: 'Lunging super-haymaker with boulder-cracking impact.',
      move: {
        name: 'Bicep Boulder Punch',
        type: 'HEAVY_PUNCH',
        startupFrames: 8,
        activeFrames: 8,
        recoveryFrames: 14,
        totalFrames: 30,
        damage: 107,
        meterGain: 22,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 8,
            duration: 8,
            offsetX: 1.45,
            offsetY: 1.35,
            width: 1.1,
            height: 0.9,
            damage: 107,
            knockbackX: 0.38,
            knockbackY: 0.08,
            hitstun: 30,
            blockstun: 16,
            isHeavy: true,
            humorText: 'BOULDER SMASH!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'bob_bulldozer_headbutt',
      name: 'Bulldozer Headbutt',
      command: 'DOUBLE_TAP_F',
      button: 'LP',
      commandDisplay: '→ → + LP',
      description: 'Dashing armored bull rush that closes distance in an instant.',
      move: {
        name: 'Bulldozer Headbutt',
        type: 'LIGHT_PUNCH',
        startupFrames: 5,
        activeFrames: 6,
        recoveryFrames: 10,
        totalFrames: 21,
        damage: 58,
        meterGain: 14,
        isHeavy: false,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 5,
            duration: 6,
            offsetX: 1.25,
            offsetY: 1.4,
            width: 0.9,
            height: 0.75,
            damage: 58,
            knockbackX: 0.25,
            knockbackY: 0.04,
            hitstun: 20,
            blockstun: 10,
            isHeavy: false,
            humorText: 'BULLDOZER!',
            soundType: 'bonk',
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: 'bob_combo_1_2',
      name: '1-2 Heavy Hook',
      fromMoveName: 'Quick Jab',
      nextButton: 'HP',
      displayChain: 'Quick Jab (LP) ➔ Heavy Hook (HP)',
      nextMove: {
        name: 'Heavy Hook Followup',
        type: 'HEAVY_PUNCH',
        startupFrames: 4,
        activeFrames: 6,
        recoveryFrames: 12,
        totalFrames: 22,
        damage: 72,
        meterGain: 15,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 4,
            duration: 6,
            offsetX: 1.2,
            offsetY: 1.4,
            width: 0.9,
            height: 0.8,
            damage: 72,
            knockbackX: 0.32,
            knockbackY: 0.06,
            hitstun: 26,
            blockstun: 14,
            isHeavy: true,
            humorText: '1-2 COMBO!',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  supers: [
    {
      id: 'bob_super_lvl1',
      name: 'Bicep Boulder Haymaker',
      level: 1,
      meterCost: 100,
      command: 'QCF',
      button: 'HP',
      commandDisplay: '↓ → + HP (Tap SUPER)',
      description: 'Level 1 Super (1 Level): Lunging super-haymaker with boulder-cracking impact.',
      move: {
        name: 'Bicep Boulder Haymaker',
        type: 'SUPER_MOVE',
        startupFrames: 8,
        activeFrames: 8,
        recoveryFrames: 14,
        totalFrames: 30,
        damage: 107,
        meterGain: 0,
        superCost: 100,
        isSuper: true,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 8,
            duration: 8,
            offsetX: 1.45,
            offsetY: 1.35,
            width: 1.1,
            height: 0.9,
            damage: 107,
            knockbackX: 0.42,
            knockbackY: 0.22,
            hitstun: 28,
            blockstun: 15,
            isHeavy: true,
            humorText: 'BOULDER BOP!',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'bob_super_lvl2',
      name: 'Heavyweight Dropkick Cyclone',
      level: 2,
      meterCost: 200,
      command: 'QCB',
      button: 'HK',
      commandDisplay: '↓ ← + HK (↓ + SUPER)',
      description: 'Level 2 Super (2 Levels): Leaping spinning dropkick cyclone with crushing weight.',
      move: {
        name: 'Heavyweight Dropkick Cyclone',
        type: 'SUPER_MOVE',
        startupFrames: 10,
        activeFrames: 16,
        recoveryFrames: 16,
        totalFrames: 42,
        damage: 172,
        meterGain: 0,
        superCost: 200,
        isSuper: true,
        isHeavy: true,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 10,
            duration: 16,
            offsetX: 1.5,
            offsetY: 1.25,
            width: 1.2,
            height: 1.0,
            damage: 172,
            knockbackX: 0.52,
            knockbackY: 0.28,
            hitstun: 35,
            blockstun: 20,
            isHeavy: true,
            humorText: 'CYCLONE YEET!',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'bob_super_lvl3',
      name: 'Tornado Bonk Barrage (ULTIMATE)',
      level: 3,
      meterCost: 300,
      command: 'DOWN_DOWN',
      button: 'HP',
      commandDisplay: '↓ ↓ + LP + HP (Hold SUPER)',
      description: 'Level 3 Ultimate (3 Levels): Triple-hit spinning tornado bonk barrage with glowing giant fists.',
      move: {
        name: 'Tornado Bonk Barrage (ULTIMATE)',
        type: 'SUPER_MOVE',
        startupFrames: 10,
        activeFrames: 34,
        recoveryFrames: 20,
        totalFrames: 64,
        damage: 247,
        meterGain: 0,
        superCost: 300,
        isSuper: true,
        isHeavy: true,
        animType: 'super',
        hitboxes: [
          {
            startFrame: 10,
            duration: 10,
            offsetX: 1.1,
            offsetY: 1.4,
            width: 0.9,
            height: 0.8,
            damage: 58,
            knockbackX: 0.12,
            knockbackY: 0.05,
            hitstun: 20,
            blockstun: 12,
            isHeavy: true,
            humorText: 'WHAM!',
            soundType: 'heavy',
          },
          {
            startFrame: 20,
            duration: 10,
            offsetX: 1.25,
            offsetY: 1.45,
            width: 1.0,
            height: 0.9,
            damage: 65,
            knockbackX: 0.14,
            knockbackY: 0.06,
            hitstun: 22,
            blockstun: 14,
            isHeavy: true,
            humorText: 'KAPOW!',
            soundType: 'heavy',
          },
          {
            startFrame: 30,
            duration: 14,
            offsetX: 1.5,
            offsetY: 1.6,
            width: 1.3,
            height: 1.2,
            damage: 124,
            knockbackX: 0.55,
            knockbackY: 0.25,
            hitstun: 40,
            blockstun: 22,
            isHeavy: true,
            humorText: 'GIGA BONK!!',
            soundType: 'super',
          },
        ],
      },
    },
  ],
  superSpecial: {
    id: 'bob_super_lvl3',
    name: 'Tornado Bonk Barrage (ULTIMATE)',
    command: 'DOWN_DOWN',
    button: 'HP',
    commandDisplay: '↓ ↓ + LP + HP (Hold SUPER)',
    description: 'Level 3 Ultimate (3 Levels): Triple-hit spinning tornado barrage.',
    move: {
      name: 'Tornado Bonk Barrage (ULTIMATE)',
      type: 'SUPER_MOVE',
      startupFrames: 10,
      activeFrames: 34,
      recoveryFrames: 20,
      totalFrames: 64,
      damage: 247,
      meterGain: 0,
      superCost: 300,
      isSuper: true,
      isHeavy: true,
      animType: 'super',
      hitboxes: [
        {
          startFrame: 10,
          duration: 10,
          offsetX: 1.1,
          offsetY: 1.4,
          width: 0.9,
          height: 0.8,
          damage: 58,
          knockbackX: 0.12,
          knockbackY: 0.05,
          hitstun: 20,
          blockstun: 12,
          isHeavy: true,
          humorText: 'WHAM!',
          soundType: 'heavy',
        },
        {
          startFrame: 20,
          duration: 10,
          offsetX: 1.25,
          offsetY: 1.45,
          width: 1.0,
          height: 0.9,
          damage: 65,
          knockbackX: 0.14,
          knockbackY: 0.06,
          hitstun: 22,
          blockstun: 14,
          isHeavy: true,
          humorText: 'KAPOW!',
          soundType: 'heavy',
        },
        {
          startFrame: 30,
          duration: 14,
          offsetX: 1.5,
          offsetY: 1.6,
          width: 1.3,
          height: 1.2,
          damage: 124,
          knockbackX: 0.55,
          knockbackY: 0.25,
          hitstun: 40,
          blockstun: 22,
          isHeavy: true,
          humorText: 'GIGA BONK!!',
          soundType: 'super',
        },
      ],
    },
  },
};

export const FIGHTER_KYLE: FighterConfig = {
  id: 'fighter_kyle',
  name: 'Karate Kyle',
  subtitle: 'Master of the Flailing Noodle Dojo',
  stats: {
    maxHealth: 920,
    walkSpeed: 0.098,
    dashSpeed: 0.205,
    jumpForce: 0.31,
    powerMultiplier: 1.02,
    weight: 0.92,
  },
  appearance: {
    primaryColor: 0x06b6d4, // Cyan gi
    secondaryColor: 0xfacc15, // Yellow trim / belt
    skinColor: 0xfcd34d, // Light warm skin
    gloveColor: 0x0891b2, // Cyan hand wraps
    hairColor: 0xf59e0b, // Yellow/golden spiky hair
    eyeColor: 0x0f172a,
    bodyType: 'slim',
    headShape: 'round',
    eyebrows: 'angry',
    mouth: 'serious',
    noseShape: 'pointy',
    noseSize: 'medium',
    hairStyle: 'spiky',
    beard: 'none',
    shirtType: 'gi',
    shirtColor: 0x06b6d4,
    pantsType: 'gi_pants',
    pantsColor: 0x06b6d4,
    shoesType: 'martial_wraps',
    shoesColor: 0xfacc15,
    gloveType: 'hand_wraps',
    accessory: 'black_belt',
    specialItem: 'black_belt',
  },
  victoryQuote: 'My flailing arms are swift like the spring breeze!',
  defeatQuote: 'My noodles... have been tangled...',
  koAnimation: {
    type: 'default_stars',
  },
  moves: {
    LIGHT_PUNCH: {
      name: 'Noodle Slap',
      type: 'LIGHT_PUNCH',
      startupFrames: 3,
      activeFrames: 4,
      recoveryFrames: 5,
      totalFrames: 12,
      damage: 26,
      meterGain: 9,
      animType: 'lp',
      hitboxes: [
        {
          startFrame: 3,
          duration: 4,
          offsetX: 0.9,
          offsetY: 1.4,
          width: 0.65,
          height: 0.5,
          damage: 26,
          knockbackX: 0.08,
          knockbackY: 0.02,
          hitstun: 11,
          blockstun: 6,
          isHeavy: false,
          humorText: 'SLAP!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_PUNCH: {
      name: 'Chop of Doom',
      type: 'HEAVY_PUNCH',
      startupFrames: 8,
      activeFrames: 5,
      recoveryFrames: 14,
      totalFrames: 27,
      damage: 77,
      meterGain: 17,
      isHeavy: true,
      animType: 'hp',
      hitboxes: [
        {
          startFrame: 8,
          duration: 5,
          offsetX: 1.15,
          offsetY: 1.5,
          width: 0.85,
          height: 0.75,
          damage: 77,
          knockbackX: 0.25,
          knockbackY: 0.14,
          hitstun: 22,
          blockstun: 13,
          isHeavy: true,
          humorText: 'WHACK!',
          soundType: 'heavy',
        },
      ],
    },
    LIGHT_KICK: {
      name: 'Toe Tickler',
      type: 'LIGHT_KICK',
      startupFrames: 4,
      activeFrames: 4,
      recoveryFrames: 6,
      totalFrames: 14,
      damage: 31,
      meterGain: 10,
      animType: 'lk',
      hitboxes: [
        {
          startFrame: 4,
          duration: 4,
          offsetX: 1.05,
          offsetY: 0.35,
          width: 0.75,
          height: 0.5,
          damage: 31,
          knockbackX: 0.09,
          knockbackY: 0.02,
          hitstun: 13,
          blockstun: 7,
          isHeavy: false,
          humorText: 'TICKLE!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_KICK: {
      name: 'Somersault Boot',
      type: 'HEAVY_KICK',
      startupFrames: 10,
      activeFrames: 6,
      recoveryFrames: 16,
      totalFrames: 32,
      damage: 86,
      meterGain: 20,
      isHeavy: true,
      animType: 'hk',
      hitboxes: [
        {
          startFrame: 10,
          duration: 6,
          offsetX: 1.25,
          offsetY: 1.35,
          width: 0.9,
          height: 0.8,
          damage: 86,
          knockbackX: 0.32,
          knockbackY: 0.24,
          hitstun: 25,
          blockstun: 14,
          isHeavy: true,
          humorText: 'KAPOW!',
          soundType: 'heavy',
        },
      ],
    },
    SUPER_MOVE: {
      name: 'Dragon Slap Hyper-Drive',
      type: 'SUPER_MOVE',
      startupFrames: 8,
      activeFrames: 36,
      recoveryFrames: 18,
      totalFrames: 62,
      damage: 211,
      meterGain: 0,
      superCost: 100,
      isSuper: true,
      isHeavy: true,
      animType: 'super',
      hitboxes: [
        {
          startFrame: 8,
          duration: 10,
          offsetX: 1.1,
          offsetY: 1.4,
          width: 0.9,
          height: 0.8,
          damage: 49,
          knockbackX: 0.1,
          knockbackY: 0.06,
          hitstun: 18,
          blockstun: 12,
          isHeavy: true,
          humorText: 'SLAP!',
          soundType: 'heavy',
        },
        {
          startFrame: 18,
          duration: 10,
          offsetX: 1.2,
          offsetY: 1.35,
          width: 0.95,
          height: 0.85,
          damage: 55,
          knockbackX: 0.12,
          knockbackY: 0.08,
          hitstun: 20,
          blockstun: 13,
          isHeavy: true,
          humorText: 'FLURRY!',
          soundType: 'heavy',
        },
        {
          startFrame: 28,
          duration: 16,
          offsetX: 1.55,
          offsetY: 1.5,
          width: 1.25,
          height: 1.1,
          damage: 107,
          knockbackX: 0.48,
          knockbackY: 0.36,
          hitstun: 35,
          blockstun: 20,
          isHeavy: true,
          humorText: 'SUPER YEET!!',
          soundType: 'super',
        },
      ],
    },
  },
  specials: [
    {
      id: 'kyle_dragon_kick',
      name: 'Dragon Noodle Kick',
      command: 'QCF',
      button: 'HK',
      commandDisplay: '↓ → + HK',
      description: 'Soaring dragon kick that reaches high into the air.',
      move: {
        name: 'Dragon Noodle Kick',
        type: 'HEAVY_KICK',
        startupFrames: 7,
        activeFrames: 8,
        recoveryFrames: 14,
        totalFrames: 29,
        damage: 101,
        meterGain: 20,
        isHeavy: true,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 7,
            duration: 8,
            offsetX: 1.4,
            offsetY: 1.5,
            width: 1.1,
            height: 1.0,
            damage: 101,
            knockbackX: 0.35,
            knockbackY: 0.08,
            hitstun: 28,
            blockstun: 15,
            isHeavy: true,
            humorText: 'DRAGON KICK!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'kyle_flurry_palms',
      name: 'Rapid Flurry Palms',
      command: 'BACK_FORWARD',
      button: 'LP',
      commandDisplay: '← → + LP',
      description: 'Rapid-fire alternating palm slaps with rapid block push.',
      move: {
        name: 'Rapid Flurry Palms',
        type: 'LIGHT_PUNCH',
        startupFrames: 5,
        activeFrames: 10,
        recoveryFrames: 10,
        totalFrames: 25,
        damage: 72,
        meterGain: 18,
        isHeavy: false,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 5,
            duration: 5,
            offsetX: 1.1,
            offsetY: 1.35,
            width: 0.85,
            height: 0.7,
            damage: 33,
            knockbackX: 0.12,
            knockbackY: 0.02,
            hitstun: 15,
            blockstun: 8,
            isHeavy: false,
            humorText: 'SLAP!',
            soundType: 'light',
          },
          {
            startFrame: 10,
            duration: 5,
            offsetX: 1.25,
            offsetY: 1.4,
            width: 0.9,
            height: 0.75,
            damage: 39,
            knockbackX: 0.22,
            knockbackY: 0.03,
            hitstun: 20,
            blockstun: 10,
            isHeavy: false,
            humorText: 'FLURRY!',
            soundType: 'light',
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: 'kyle_combo_kick',
      name: 'Shin-to-Dragon Kick',
      fromMoveName: 'Noodle Shin Kick',
      nextButton: 'HK',
      displayChain: 'Noodle Shin Kick (LK) ➔ Dragon Kick (HK)',
      nextMove: {
        name: 'Dragon High Kick Followup',
        type: 'HEAVY_KICK',
        startupFrames: 4,
        activeFrames: 6,
        recoveryFrames: 12,
        totalFrames: 22,
        damage: 75,
        meterGain: 15,
        isHeavy: true,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 4,
            duration: 6,
            offsetX: 1.3,
            offsetY: 1.5,
            width: 1.0,
            height: 0.9,
            damage: 75,
            knockbackX: 0.32,
            knockbackY: 0.06,
            hitstun: 25,
            blockstun: 14,
            isHeavy: true,
            humorText: 'KICK COMBO!',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  supers: [
    {
      id: 'kyle_super_lvl1',
      name: 'Flailing Noodle Flurry',
      level: 1,
      meterCost: 100,
      command: 'QCF',
      button: 'HP',
      commandDisplay: '↓ → + HP (Tap SUPER)',
      description: 'Level 1 Super (1 Level): Rapid-fire 20-slap flailing flurry rushing across the floor.',
      move: {
        name: 'Flailing Noodle Flurry',
        type: 'SUPER_MOVE',
        startupFrames: 6,
        activeFrames: 18,
        recoveryFrames: 12,
        totalFrames: 36,
        damage: 101,
        meterGain: 0,
        superCost: 100,
        isSuper: true,
        isHeavy: true,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 6,
            duration: 18,
            offsetX: 1.35,
            offsetY: 1.4,
            width: 1.0,
            height: 0.8,
            damage: 101,
            knockbackX: 0.38,
            knockbackY: 0.18,
            hitstun: 26,
            blockstun: 14,
            isHeavy: true,
            humorText: 'FLURRY SLAP!',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'kyle_super_lvl2',
      name: 'Dragon Somersault Yeet',
      level: 2,
      meterCost: 200,
      command: 'QCB',
      button: 'HK',
      commandDisplay: '↓ ← + HK (↓ + SUPER)',
      description: 'Level 2 Super (2 Levels): High-flying spinning somersault dropkick across the ring.',
      move: {
        name: 'Dragon Somersault Yeet',
        type: 'SUPER_MOVE',
        startupFrames: 9,
        activeFrames: 16,
        recoveryFrames: 16,
        totalFrames: 41,
        damage: 166,
        meterGain: 0,
        superCost: 200,
        isSuper: true,
        isHeavy: true,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 9,
            duration: 16,
            offsetX: 1.45,
            offsetY: 1.3,
            width: 1.15,
            height: 0.95,
            damage: 166,
            knockbackX: 0.5,
            knockbackY: 0.28,
            hitstun: 35,
            blockstun: 20,
            isHeavy: true,
            humorText: 'DRAGON YEET!',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'kyle_super_lvl3',
      name: 'Dragon Slap Hyper-Drive (ULTIMATE)',
      level: 3,
      meterCost: 300,
      command: 'DOWN_DOWN',
      button: 'HK',
      commandDisplay: '↓ ↓ + LP + HP (Hold SUPER)',
      description: 'Level 3 Ultimate (3 Levels): Blistering martial flurry followed by a comic grand finale.',
      move: {
        name: 'Dragon Slap Hyper-Drive (ULTIMATE)',
        type: 'SUPER_MOVE',
        startupFrames: 8,
        activeFrames: 36,
        recoveryFrames: 18,
        totalFrames: 62,
        damage: 244,
        meterGain: 0,
        superCost: 300,
        isSuper: true,
        isHeavy: true,
        animType: 'super',
        hitboxes: [
          {
            startFrame: 8,
            duration: 10,
            offsetX: 1.1,
            offsetY: 1.4,
            width: 0.9,
            height: 0.8,
            damage: 55,
            knockbackX: 0.1,
            knockbackY: 0.05,
            hitstun: 18,
            blockstun: 12,
            isHeavy: true,
            humorText: 'SLAP!',
            soundType: 'heavy',
          },
          {
            startFrame: 18,
            duration: 10,
            offsetX: 1.2,
            offsetY: 1.35,
            width: 0.95,
            height: 0.85,
            damage: 62,
            knockbackX: 0.12,
            knockbackY: 0.06,
            hitstun: 20,
            blockstun: 13,
            isHeavy: true,
            humorText: 'FLURRY!',
            soundType: 'heavy',
          },
          {
            startFrame: 28,
            duration: 16,
            offsetX: 1.55,
            offsetY: 1.5,
            width: 1.25,
            height: 1.1,
            damage: 127,
            knockbackX: 0.55,
            knockbackY: 0.25,
            hitstun: 40,
            blockstun: 22,
            isHeavy: true,
            humorText: 'SUPER YEET!!',
            soundType: 'super',
          },
        ],
      },
    },
  ],
  superSpecial: {
    id: 'kyle_super_lvl3',
    name: 'Dragon Slap Hyper-Drive (ULTIMATE)',
    command: 'DOWN_DOWN',
    button: 'HK',
    commandDisplay: '↓ ↓ + LP + HP (Hold SUPER)',
    description: 'Level 3 Ultimate (3 Levels): Blistering martial flurry followed by a comic grand finale.',
    move: {
      name: 'Dragon Slap Hyper-Drive (ULTIMATE)',
      type: 'SUPER_MOVE',
      startupFrames: 8,
      activeFrames: 36,
      recoveryFrames: 18,
      totalFrames: 62,
      damage: 244,
      meterGain: 0,
      superCost: 300,
      isSuper: true,
      isHeavy: true,
      animType: 'super',
      hitboxes: [
        {
          startFrame: 8,
          duration: 10,
          offsetX: 1.1,
          offsetY: 1.4,
          width: 0.9,
          height: 0.8,
          damage: 55,
          knockbackX: 0.1,
          knockbackY: 0.05,
          hitstun: 18,
          blockstun: 12,
          isHeavy: true,
          humorText: 'SLAP!',
          soundType: 'heavy',
        },
        {
          startFrame: 18,
          duration: 10,
          offsetX: 1.2,
          offsetY: 1.35,
          width: 0.95,
          height: 0.85,
          damage: 62,
          knockbackX: 0.12,
          knockbackY: 0.06,
          hitstun: 20,
          blockstun: 13,
          isHeavy: true,
          humorText: 'FLURRY!',
          soundType: 'heavy',
        },
        {
          startFrame: 28,
          duration: 16,
          offsetX: 1.55,
          offsetY: 1.5,
          width: 1.25,
          height: 1.1,
          damage: 127,
          knockbackX: 0.55,
          knockbackY: 0.25,
          hitstun: 40,
          blockstun: 22,
          isHeavy: true,
          humorText: 'SUPER YEET!!',
          soundType: 'super',
        },
      ],
    },
  },
};

export const FIGHTER_DANDAN: FighterConfig = {
  id: 'fighter_dandan',
  name: 'Dandan "Sodaniel"',
  subtitle: 'The Trickster Handyman',
  stats: {
    maxHealth: 900, // Health 90 (trickster archetype)
    walkSpeed: 0.108, // Speed 9/10 (fast, evasive)
    dashSpeed: 0.225,
    jumpForce: 0.30, // Jump 7/10
    powerMultiplier: 0.85, // Power 5/10 (low damage, relies on tricks & combos)
    weight: 0.88,
  },
  appearance: {
    primaryColor: 0x323f37, // Dark gray-green work pants
    secondaryColor: 0xd97706, // Mustard-gold trim & graphic print
    skinColor: 0x7A4A2E, // Deep dark brown (#7A4A2E)
    gloveColor: 0xffffff, // White work gloves
    cuffColor: 0xef4444, // Red cuffs
    hairColor: 0x1E1510, // Dark faux-hawk ridge (#1E1510)
    eyeColor: 0x1E1510, // Friendly eyes
    graphicColor: 0xd97706, // Mustard-gold rectangle chest print
    bodyType: 'slim', // Slim, lanky
    headShape: 'oval', // Slightly oval (taller than wide)
    eyebrows: 'arched', // Thin dark eyebrows
    mouth: 'grin', // BIG wide smile showing teeth
    noseShape: 'pointy', // Skin-colored cone pointing forward
    noseSize: 'large', // Funny big cone nose, visible in profile
    hairStyle: 'faux-hawk', // Tall narrow ridge, shaved sides with no volume
    beard: 'none',
    shirtType: 'tshirt', // Loose white t-shirt with mustard-gold rectangle
    shirtColor: 0xffffff,
    pantsType: 'long_pants', // Dark gray-green work pants
    pantsColor: 0x323f37,
    shoesType: 'boxing_boots', // Work boots
    shoesColor: 0x54361c,
    gloveType: 'work_gloves', // White with red cuffs
    accessory: 'tool_belt', // Tool belt with wrench & duct tape
  },
  victoryQuote: 'Told you so! A roll of duct tape and elbow grease fixes everything!',
  defeatQuote: 'Wait, timeout! My wrench slipped... and that wasn\'t me anyway!',
  koAnimation: {
    type: 'dandan_dart',
    quote: "It wasn't me...",
  },
  moves: {
    LIGHT_PUNCH: {
      name: 'Quick Jab',
      type: 'LIGHT_PUNCH',
      startupFrames: 3,
      activeFrames: 4,
      recoveryFrames: 5,
      totalFrames: 12,
      damage: 34,
      meterGain: 8,
      animType: 'lp',
      hitboxes: [
        {
          startFrame: 3,
          duration: 4,
          offsetX: 0.88,
          offsetY: 1.45,
          width: 0.65,
          height: 0.5,
          damage: 34,
          knockbackX: 0.08,
          knockbackY: 0.02,
          hitstun: 12,
          blockstun: 7,
          isHeavy: false,
          humorText: 'POKE!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_PUNCH: {
      name: 'Wrench Swing',
      type: 'HEAVY_PUNCH',
      startupFrames: 8,
      activeFrames: 6,
      recoveryFrames: 14,
      totalFrames: 28,
      damage: 82,
      meterGain: 14,
      isHeavy: true,
      animType: 'wrench_swing',
      hitboxes: [
        {
          startFrame: 8,
          duration: 6,
          offsetX: 1.25,
          offsetY: 1.42,
          width: 0.95,
          height: 0.85,
          damage: 82,
          knockbackX: 0.24,
          knockbackY: 0.12,
          hitstun: 22,
          blockstun: 13,
          isHeavy: true,
          humorText: 'CLANG!',
          soundType: 'heavy',
        },
      ],
    },
    LIGHT_KICK: {
      name: 'Low Shin Kick',
      type: 'LIGHT_KICK',
      startupFrames: 4,
      activeFrames: 4,
      recoveryFrames: 6,
      totalFrames: 14,
      damage: 36,
      meterGain: 8,
      animType: 'lk',
      hitboxes: [
        {
          startFrame: 4,
          duration: 4,
          offsetX: 0.92,
          offsetY: 0.42,
          width: 0.72,
          height: 0.52,
          damage: 36,
          knockbackX: 0.07,
          knockbackY: 0.02,
          hitstun: 12,
          blockstun: 7,
          isHeavy: false,
          humorText: 'TRIP!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_KICK: {
      name: 'Spinning Kick',
      type: 'HEAVY_KICK',
      startupFrames: 9,
      activeFrames: 8,
      recoveryFrames: 15,
      totalFrames: 32,
      damage: 88,
      meterGain: 16,
      isHeavy: true,
      animType: 'hk',
      hitboxes: [
        {
          startFrame: 9,
          duration: 8,
          offsetX: 1.25,
          offsetY: 1.35,
          width: 0.95,
          height: 0.85,
          damage: 88,
          knockbackX: 0.32,
          knockbackY: 0.18,
          hitstun: 24,
          blockstun: 14,
          isHeavy: true,
          humorText: 'SWISH!',
          soundType: 'heavy',
        },
      ],
    },
    SUPER_MOVE: {
      name: 'The Big Lie',
      type: 'SUPER_MOVE',
      startupFrames: 8,
      activeFrames: 30,
      recoveryFrames: 18,
      totalFrames: 56,
      damage: 153,
      meterGain: 0,
      superCost: 100,
      isSuper: true,
      isHeavy: true,
      animType: 'the_big_lie',
      hitboxes: [
        {
          startFrame: 8,
          duration: 14,
          offsetX: 1.8,
          offsetY: 1.5,
          width: 1.8,
          height: 0.9,
          damage: 75,
          knockbackX: 0.15,
          knockbackY: 0.08,
          hitstun: 24,
          blockstun: 15,
          isHeavy: true,
          humorText: 'PINOCCHIO!',
          soundType: 'super',
        },
        {
          startFrame: 22,
          duration: 16,
          offsetX: 1.9,
          offsetY: 1.45,
          width: 2.0,
          height: 1.1,
          damage: 78,
          knockbackX: 0.45,
          knockbackY: 0.22,
          hitstun: 35,
          blockstun: 20,
          isHeavy: true,
          humorText: 'TOOL BOX SMASH!!',
          soundType: 'super',
        },
      ],
    },
  },
  specials: [
    {
      id: 'dandan_nose_poke',
      name: 'Nose Poke',
      command: 'DOUBLE_TAP_F',
      button: 'HP',
      commandDisplay: '→ → + HP',
      description: 'Lunging headbutt with the big nose, long reach',
      move: {
        name: 'Nose Poke',
        type: 'HEAVY_PUNCH',
        startupFrames: 7,
        activeFrames: 8,
        recoveryFrames: 13,
        totalFrames: 28,
        damage: 68,
        meterGain: 15,
        isHeavy: true,
        animType: 'nose_poke',
        hitboxes: [
          {
            startFrame: 7,
            duration: 8,
            offsetX: 1.55,
            offsetY: 1.52,
            width: 1.25,
            height: 0.8,
            damage: 68,
            knockbackX: 0.35,
            knockbackY: 0.12,
            hitstun: 25,
            blockstun: 14,
            isHeavy: true,
            humorText: 'SNOOT BOP!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'dandan_duct_tape_toss',
      name: 'Duct Tape Toss',
      command: 'QCF',
      button: 'LP',
      commandDisplay: '↓ → + LP',
      description: 'Throws the tape roll as a projectile, hit opponent is slowed for 2 sec',
      move: {
        name: 'Duct Tape Toss',
        type: 'LIGHT_PUNCH',
        startupFrames: 6,
        activeFrames: 6,
        recoveryFrames: 12,
        totalFrames: 24,
        damage: 42,
        meterGain: 12,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 6,
            duration: 6,
            offsetX: 1.1,
            offsetY: 1.4,
            width: 0.75,
            height: 0.6,
            damage: 42,
            knockbackX: 0.12,
            knockbackY: 0.05,
            hitstun: 18,
            blockstun: 10,
            isHeavy: false,
            humorText: 'STICKY TAPE!',
            soundType: 'light',
          },
        ],
      },
    },
    {
      id: 'dandan_it_wasnt_me',
      name: "It Wasn't Me!",
      command: 'DOWN_DOWN',
      button: 'HK',
      commandDisplay: '↓ ↓ + HK',
      description: 'Fakes a KO and falls; if hit within 1 sec, auto-counter with a wrench uppercut',
      move: {
        name: "It Wasn't Me!",
        type: 'HEAVY_KICK',
        startupFrames: 4,
        activeFrames: 35,
        recoveryFrames: 15,
        totalFrames: 54,
        damage: 0,
        meterGain: 10,
        animType: 'fake_ko',
        hitboxes: [],
      },
    },
    {
      id: 'dandan_maintenance_drill',
      name: 'Maintenance Drill',
      command: 'BACK_FORWARD',
      button: 'LK',
      commandDisplay: '← → + LK',
      description: 'Dashes forward with a power drill, multi-hit',
      move: {
        name: 'Maintenance Drill',
        type: 'LIGHT_KICK',
        startupFrames: 6,
        activeFrames: 20,
        recoveryFrames: 14,
        totalFrames: 40,
        damage: 85,
        meterGain: 20,
        isHeavy: true,
        animType: 'drill',
        hitboxes: [
          {
            startFrame: 6,
            duration: 5,
            offsetX: 1.15,
            offsetY: 1.35,
            width: 0.8,
            height: 0.7,
            damage: 21,
            knockbackX: 0.08,
            knockbackY: 0.02,
            hitstun: 14,
            blockstun: 10,
            isHeavy: false,
            humorText: 'BZZZZT!',
            soundType: 'light',
          },
          {
            startFrame: 12,
            duration: 5,
            offsetX: 1.25,
            offsetY: 1.35,
            width: 0.85,
            height: 0.7,
            damage: 25,
            knockbackX: 0.1,
            knockbackY: 0.03,
            hitstun: 16,
            blockstun: 11,
            isHeavy: false,
            humorText: 'DRILL!',
            soundType: 'light',
          },
          {
            startFrame: 18,
            duration: 8,
            offsetX: 1.45,
            offsetY: 1.4,
            width: 1.05,
            height: 0.85,
            damage: 39,
            knockbackX: 0.38,
            knockbackY: 0.16,
            hitstun: 26,
            blockstun: 15,
            isHeavy: true,
            humorText: 'POWER DRILL!!',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: 'dandan_combo_1',
      name: '1-2 Wrench Swing',
      fromMoveName: 'Quick Jab',
      nextButton: 'LP',
      nextMove: {
        name: 'Quick Jab 2',
        type: 'LIGHT_PUNCH',
        startupFrames: 3,
        activeFrames: 4,
        recoveryFrames: 5,
        totalFrames: 12,
        damage: 23,
        meterGain: 8,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 3,
            duration: 4,
            offsetX: 0.95,
            offsetY: 1.45,
            width: 0.7,
            height: 0.5,
            damage: 23,
            knockbackX: 0.09,
            knockbackY: 0.02,
            hitstun: 14,
            blockstun: 8,
            isHeavy: false,
            humorText: 'JAB 2!',
            soundType: 'light',
          },
        ],
      },
      displayChain: 'LP ➔ LP ➔ HP (Wrench Finisher)',
    },
    {
      id: 'dandan_combo_1_finish',
      name: 'Wrench Finisher',
      fromMoveName: 'Quick Jab 2',
      nextButton: 'HP',
      nextMove: {
        name: 'Wrench Swing',
        type: 'HEAVY_PUNCH',
        startupFrames: 6,
        activeFrames: 6,
        recoveryFrames: 12,
        totalFrames: 24,
        damage: 57,
        meterGain: 14,
        isHeavy: true,
        animType: 'wrench_swing',
        hitboxes: [
          {
            startFrame: 6,
            duration: 6,
            offsetX: 1.3,
            offsetY: 1.42,
            width: 1.0,
            height: 0.85,
            damage: 57,
            knockbackX: 0.35,
            knockbackY: 0.16,
            hitstun: 26,
            blockstun: 15,
            isHeavy: true,
            humorText: 'WRENCH SMACK!',
            soundType: 'heavy',
          },
        ],
      },
      displayChain: 'Quick Jab 2 ➔ Wrench Swing',
    },
    {
      id: 'dandan_combo_launcher',
      name: 'Trickster Full Sequence',
      fromMoveName: 'Quick Jab',
      nextButton: 'LK',
      nextMove: {
        name: 'Low Shin Kick',
        type: 'LIGHT_KICK',
        startupFrames: 3,
        activeFrames: 4,
        recoveryFrames: 5,
        totalFrames: 12,
        damage: 25,
        meterGain: 8,
        animType: 'lk',
        hitboxes: [
          {
            startFrame: 3,
            duration: 4,
            offsetX: 0.95,
            offsetY: 0.4,
            width: 0.75,
            height: 0.55,
            damage: 25,
            knockbackX: 0.08,
            knockbackY: 0.02,
            hitstun: 14,
            blockstun: 8,
            isHeavy: false,
            humorText: 'SHIN!',
            soundType: 'light',
          },
        ],
      },
      displayChain: 'LP ➔ LK ➔ HK ➔ HP Launcher',
    },
    {
      id: 'dandan_combo_launcher_hk',
      name: 'Spin Kick Chain',
      fromMoveName: 'Low Shin Kick',
      nextButton: 'HK',
      nextMove: {
        name: 'Spinning Kick',
        type: 'HEAVY_KICK',
        startupFrames: 6,
        activeFrames: 6,
        recoveryFrames: 10,
        totalFrames: 22,
        damage: 42,
        meterGain: 12,
        isHeavy: true,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 6,
            duration: 6,
            offsetX: 1.25,
            offsetY: 1.35,
            width: 0.95,
            height: 0.85,
            damage: 42,
            knockbackX: 0.18,
            knockbackY: 0.08,
            hitstun: 18,
            blockstun: 11,
            isHeavy: true,
            humorText: 'BELT SPIN!',
            soundType: 'heavy',
          },
        ],
      },
      displayChain: 'LK ➔ HK ➔ Wrench Launcher',
    },
    {
      id: 'dandan_combo_launcher_finish',
      name: 'Wrench Launcher',
      fromMoveName: 'Spinning Kick',
      nextButton: 'HP',
      nextMove: {
        name: 'Wrench Launcher',
        type: 'HEAVY_PUNCH',
        startupFrames: 6,
        activeFrames: 6,
        recoveryFrames: 14,
        totalFrames: 26,
        damage: 62,
        meterGain: 16,
        isHeavy: true,
        animType: 'wrench_launcher',
        hitboxes: [
          {
            startFrame: 6,
            duration: 6,
            offsetX: 1.2,
            offsetY: 1.6,
            width: 1.05,
            height: 1.1,
            damage: 62,
            knockbackX: 0.1,
            knockbackY: 0.38, // Sends opponent flying up into the air!
            hitstun: 32,
            blockstun: 16,
            isHeavy: true,
            humorText: 'LAUNCHER!!',
            soundType: 'heavy',
          },
        ],
      },
      displayChain: 'HK ➔ Wrench Launcher (Sends Opponent UP!)',
    },
    {
      id: 'dandan_air_juggle_1',
      name: 'Air Wrench Juggle 1',
      fromMoveName: 'Wrench Launcher',
      nextButton: 'HP',
      nextMove: {
        name: 'Air Wrench Juggle',
        type: 'HEAVY_PUNCH',
        startupFrames: 4,
        activeFrames: 6,
        recoveryFrames: 8,
        totalFrames: 18,
        damage: 49,
        meterGain: 12,
        isHeavy: true,
        animType: 'wrench_swing',
        hitboxes: [
          {
            startFrame: 4,
            duration: 6,
            offsetX: 1.15,
            offsetY: 1.65,
            width: 1.1,
            height: 1.1,
            damage: 49,
            knockbackX: 0.12,
            knockbackY: 0.22,
            hitstun: 26,
            blockstun: 14,
            isHeavy: true,
            humorText: 'AIR JUGGLE!',
            soundType: 'heavy',
          },
        ],
      },
      displayChain: 'After Launcher: HP ➔ HP (Air Wrench Juggle)',
    },
    {
      id: 'dandan_air_juggle_2',
      name: 'Air Wrench Slam',
      fromMoveName: 'Air Wrench Juggle',
      nextButton: 'HP',
      nextMove: {
        name: 'Air Wrench Slam',
        type: 'HEAVY_PUNCH',
        startupFrames: 5,
        activeFrames: 6,
        recoveryFrames: 10,
        totalFrames: 21,
        damage: 59,
        meterGain: 14,
        isHeavy: true,
        animType: 'wrench_swing',
        hitboxes: [
          {
            startFrame: 5,
            duration: 6,
            offsetX: 1.25,
            offsetY: 1.6,
            width: 1.15,
            height: 1.1,
            damage: 59,
            knockbackX: 0.25,
            knockbackY: -0.15,
            hitstun: 30,
            blockstun: 16,
            isHeavy: true,
            humorText: 'SLAM DUNK!',
            soundType: 'heavy',
          },
        ],
      },
      displayChain: 'Air Juggle ➔ HP Air Wrench Slam',
    },
  ],
  supers: [
    {
      id: 'dandan_super_lvl1',
      name: 'The Big Lie',
      level: 1,
      meterCost: 100,
      command: 'QCF',
      button: 'HP',
      commandDisplay: '↓ → + HP (Tap SUPER)',
      description: 'Level 1 Super (1 Level): He says "I swear it\'s true!", his nose grows across the screen, stabbing the opponent!',
      move: {
        name: 'The Big Lie',
        type: 'SUPER_MOVE',
        startupFrames: 10,
        activeFrames: 28,
        recoveryFrames: 18,
        totalFrames: 56,
        damage: 98,
        meterGain: 0,
        superCost: 100,
        isSuper: true,
        isHeavy: true,
        animType: 'the_big_lie',
        hitboxes: [
          {
            startFrame: 10,
            duration: 28,
            offsetX: 2.2,
            offsetY: 1.25,
            width: 3.2,
            height: 0.9,
            damage: 98,
            knockbackX: 0.45,
            knockbackY: 0.2,
            hitstun: 32,
            blockstun: 16,
            isHeavy: true,
            humorText: "I SWEAR IT'S TRUE!",
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'dandan_super_lvl2',
      name: 'SERVICE CALL!',
      level: 2,
      meterCost: 200,
      command: 'QCB',
      button: 'HK',
      commandDisplay: '↓ ← + HK (↓ + SUPER)',
      description: 'Level 2 Super (2 Levels): Dandan drives his white commercial service van into the ring, honks the horn ("BEEP BEEP!"), runs over the opponent flattening them like a pancake, leans out the window shouting "Technician has arrived!", and drives off.',
      move: {
        name: 'SERVICE CALL!',
        type: 'SUPER_MOVE',
        startupFrames: 10,
        activeFrames: 26,
        recoveryFrames: 20,
        totalFrames: 56,
        damage: 169,
        meterGain: 0,
        superCost: 200,
        isSuper: true,
        isHeavy: true,
        animType: 'service_van',
        hitboxes: [
          {
            startFrame: 10,
            duration: 26,
            offsetX: 1.8,
            offsetY: 1.2,
            width: 1.8,
            height: 1.2,
            damage: 169,
            knockbackX: 0.55,
            knockbackY: 0.35,
            hitstun: 40,
            blockstun: 20,
            isHeavy: true,
            humorText: 'BEEP BEEP!',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'dandan_super_lvl3',
      name: 'Jasmine Power (ULTIMATE)',
      level: 3,
      meterCost: 300,
      command: 'DOWN_DOWN',
      button: 'HP',
      commandDisplay: '↓ ↓ + LP + HP (Hold SUPER 1s)',
      description: 'Level 3 Ultimate (3 Levels): "I LOVE YOU JASMINE!" Kamikaze rocket dive with heart burst! Massive damage.',
      move: {
        name: 'Jasmine Power',
        type: 'SUPER_MOVE',
        startupFrames: 12,
        activeFrames: 30,
        recoveryFrames: 20,
        totalFrames: 62,
        damage: 273,
        meterGain: 0,
        superCost: 300,
        isSuper: true,
        isHeavy: true,
        animType: 'rocket_dive',
        hitboxes: [
          {
            startFrame: 12,
            duration: 30,
            offsetX: 1.8,
            offsetY: 1.2,
            width: 1.6,
            height: 1.3,
            damage: 273,
            knockbackX: 0.65,
            knockbackY: 0.35,
            hitstun: 45,
            blockstun: 25,
            isHeavy: true,
            humorText: 'I LOVE YOU JASMINE!!!',
            soundType: 'super',
          },
        ],
      },
    },
  ],
  superSpecial: {
    id: 'dandan_jasmine_power',
    name: 'Jasmine Power (ULTIMATE)',
    command: 'DOWN_DOWN',
    button: 'HP',
    commandDisplay: '↓↓ + LP+HP (Hold SUPER 1s)',
    description: 'Level 3 Ultimate (3 Levels): "I LOVE YOU JASMINE!" Kamikaze rocket dive with heart burst! Massive damage.',
    move: {
      name: 'Jasmine Power',
      type: 'SUPER_MOVE',
      startupFrames: 12,
      activeFrames: 30,
      recoveryFrames: 20,
      totalFrames: 62,
      damage: 273,
      meterGain: 0,
      superCost: 300,
      isSuper: true,
      isHeavy: true,
      animType: 'rocket_dive',
      hitboxes: [
        {
          startFrame: 12,
          duration: 30,
          offsetX: 1.8,
          offsetY: 1.2,
          width: 1.6,
          height: 1.3,
          damage: 273,
          knockbackX: 0.65,
          knockbackY: 0.35,
          hitstun: 45,
          blockstun: 25,
          isHeavy: true,
          humorText: 'I LOVE YOU JASMINE!!!',
          soundType: 'super',
        },
      ],
    },
  },
};

export const FIGHTER_MOSHON: FighterConfig = {
  id: 'fighter_moshon',
  name: 'Moshon "The Eliminator from Holon"',
  subtitle: 'The Eliminator from Holon',
  stats: {
    maxHealth: 1050, // Health 105 (tanky power fighter)
    walkSpeed: 0.088, // Speed 6/10
    dashSpeed: 0.190,
    jumpForce: 0.27, // Jump 5/10
    powerMultiplier: 1.15, // Power 8/10 (heavy hitting, strong strikes)
    weight: 1.05,
  },
  appearance: {
    primaryColor: 0x18181b, // Black pants
    secondaryColor: 0x15803d, // Maccabi green circular patch
    skinColor: 0xd2a27e, // Light olive Mediterranean skin tone (#D2A27E)
    gloveColor: 0xd2a27e, // Bare hands skin tone (#D2A27E)
    hairColor: 0x2a1c14, // Short dark brown (#2A1C14)
    eyeColor: 0x18181b,
    graphicColor: 0x15803d, // Green club badge
    cuffColor: 0x334155, // Dark slate gray shoulder panels
    bodyType: 'average', // Lean athletic build
    headShape: 'oval', // Slightly oval with elf-like pointy ears
    eyebrows: 'normal',
    mouth: 'smile', // Small subtle smile
    noseShape: 'pointy',
    noseSize: 'medium',
    hairStyle: 'short', // Short neat dark brown hair with slightly high hairline (#2A1C14)
    beard: 'full', // Short full dark brown beard and mustache (#2A1C14)
    shirtType: 'tshirt', // Black zip-up track jacket with gray shoulders & light gray collar
    shirtColor: 0x121214, // Black jacket
    pantsType: 'long_pants', // Black pants
    pantsColor: 0x18181b,
    shoesType: 'sneakers', // Dark sneakers
    shoesColor: 0x18181b,
    gloveType: 'bare_hands',
    accessory: 'glasses', // Thick black rectangular frames & gold necklace chain
  },
  victoryQuote: 'Nobody takes my parking spot in Holon. You have been eliminated.',
  defeatQuote: 'My glasses... has anyone seen my glasses on the canvas?',
  koAnimation: {
    type: 'moshon_phone',
    quote: 'LINOY CALLING',
  },
  moves: {
    LIGHT_PUNCH: {
      name: 'Straight Jab',
      type: 'LIGHT_PUNCH',
      startupFrames: 4,
      activeFrames: 4,
      recoveryFrames: 6,
      totalFrames: 14,
      damage: 27,
      meterGain: 8,
      animType: 'lp',
      hitboxes: [
        {
          startFrame: 4,
          duration: 4,
          offsetX: 0.95,
          offsetY: 1.45,
          width: 0.7,
          height: 0.55,
          damage: 27,
          knockbackX: 0.08,
          knockbackY: 0.02,
          hitstun: 13,
          blockstun: 7,
          isHeavy: false,
          humorText: 'JAB!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_PUNCH: {
      name: 'Heavy Overhand',
      type: 'HEAVY_PUNCH',
      startupFrames: 9,
      activeFrames: 6,
      recoveryFrames: 16,
      totalFrames: 31,
      damage: 81,
      meterGain: 18,
      isHeavy: true,
      animType: 'hp',
      hitboxes: [
        {
          startFrame: 9,
          duration: 6,
          offsetX: 1.25,
          offsetY: 1.4,
          width: 0.95,
          height: 0.85,
          damage: 81,
          knockbackX: 0.3,
          knockbackY: 0.16,
          hitstun: 25,
          blockstun: 14,
          isHeavy: true,
          humorText: 'OVERHAND!',
          soundType: 'heavy',
        },
      ],
    },
    LIGHT_KICK: {
      name: 'Stomp Kick',
      type: 'LIGHT_KICK',
      startupFrames: 5,
      activeFrames: 5,
      recoveryFrames: 7,
      totalFrames: 17,
      damage: 33,
      meterGain: 10,
      animType: 'lk',
      hitboxes: [
        {
          startFrame: 5,
          duration: 5,
          offsetX: 1.0,
          offsetY: 0.35,
          width: 0.75,
          height: 0.55,
          damage: 33,
          knockbackX: 0.09,
          knockbackY: 0.02,
          hitstun: 14,
          blockstun: 8,
          isHeavy: false,
          humorText: 'STOMP!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_KICK: {
      name: 'Big Roundhouse',
      type: 'HEAVY_KICK',
      startupFrames: 11,
      activeFrames: 7,
      recoveryFrames: 17,
      totalFrames: 35,
      damage: 88,
      meterGain: 20,
      isHeavy: true,
      animType: 'hk',
      hitboxes: [
        {
          startFrame: 11,
          duration: 7,
          offsetX: 1.35,
          offsetY: 1.25,
          width: 1.0,
          height: 0.85,
          damage: 88,
          knockbackX: 0.35,
          knockbackY: 0.22,
          hitstun: 26,
          blockstun: 15,
          isHeavy: true,
          humorText: 'ROUNDHOUSE!',
          soundType: 'heavy',
        },
      ],
    },
    SUPER_MOVE: {
      name: 'SHORT CIRCUIT',
      type: 'SUPER_MOVE',
      startupFrames: 8,
      activeFrames: 28,
      recoveryFrames: 16,
      totalFrames: 52,
      damage: 111,
      meterGain: 0,
      superCost: 100,
      isSuper: true,
      isHeavy: true,
      animType: 'short_circuit',
      hitboxes: [
        {
          startFrame: 8,
          duration: 28,
          offsetX: 1.45,
          offsetY: 1.35,
          width: 1.15,
          height: 0.95,
          damage: 111,
          knockbackX: 0.45,
          knockbackY: 0.2,
          hitstun: 30,
          blockstun: 16,
          isHeavy: true,
          humorText: 'ZZZAP!',
          soundType: 'super',
        },
      ],
    },
  },
  specials: [
    {
      id: 'moshon_car_door_slam',
      name: 'Car Door Slam',
      command: 'DOUBLE_TAP_F',
      button: 'HP',
      commandDisplay: '→ → + HP',
      description: 'A white car door appears and he slams it into the opponent with heavy crushing force!',
      move: {
        name: 'Car Door Slam',
        type: 'HEAVY_PUNCH',
        startupFrames: 8,
        activeFrames: 8,
        recoveryFrames: 16,
        totalFrames: 32,
        damage: 94,
        meterGain: 20,
        isHeavy: true,
        animType: 'car_door',
        hitboxes: [
          {
            startFrame: 8,
            duration: 8,
            offsetX: 1.5,
            offsetY: 1.3,
            width: 1.25,
            height: 1.1,
            damage: 94,
            knockbackX: 0.38,
            knockbackY: 0.16,
            hitstun: 26,
            blockstun: 15,
            isHeavy: true,
            humorText: 'DOOR SLAM!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'moshon_glasses_glint',
      name: 'Glasses Glint',
      command: 'DOWN_DOWN',
      button: 'LP',
      commandDisplay: '↓ ↓ + LP',
      description: 'Pushes up his glasses with a blinding anime glint! His next attack inflicts double damage.',
      move: {
        name: 'Glasses Glint',
        type: 'LIGHT_PUNCH',
        startupFrames: 6,
        activeFrames: 12,
        recoveryFrames: 10,
        totalFrames: 28,
        damage: 0,
        meterGain: 15,
        animType: 'lp',
        hitboxes: [],
      },
    },
    {
      id: 'moshon_ear_radar',
      name: 'Ear Radar',
      command: 'QCB',
      button: 'LK',
      commandDisplay: '↓ ← + LK',
      description: 'His pointy ears twitch with high-tech radar senses! Auto-counters any incoming strike with a headbutt.',
      move: {
        name: 'Ear Radar',
        type: 'LIGHT_KICK',
        startupFrames: 3,
        activeFrames: 24,
        recoveryFrames: 8,
        totalFrames: 35,
        damage: 0,
        meterGain: 12,
        animType: 'lk',
        hitboxes: [],
      },
    },
    {
      id: 'moshon_zipper_uppercut',
      name: 'Zipper Uppercut',
      command: 'QCF',
      button: 'HK',
      commandDisplay: '↓ → + HK',
      description: 'Zips up his jacket in one swift motion into a soaring launch uppercut!',
      move: {
        name: 'Zipper Uppercut',
        type: 'HEAVY_KICK',
        startupFrames: 7,
        activeFrames: 8,
        recoveryFrames: 16,
        totalFrames: 31,
        damage: 85,
        meterGain: 18,
        isHeavy: true,
        animType: 'wrench_launcher',
        hitboxes: [
          {
            startFrame: 7,
            duration: 8,
            offsetX: 1.25,
            offsetY: 1.6,
            width: 1.1,
            height: 1.1,
            damage: 85,
            knockbackX: 0.12,
            knockbackY: 0.38,
            hitstun: 32,
            blockstun: 16,
            isHeavy: true,
            humorText: 'ZIPPER UPPERCUT!',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: 'moshon_combo_1_jab',
      name: 'Jab Extension',
      fromMoveName: 'Straight Jab',
      nextButton: 'LP',
      displayChain: 'Straight Jab (LP) ➔ Jab Extension (LP)',
      nextMove: {
        name: 'Jab Extension',
        type: 'LIGHT_PUNCH',
        startupFrames: 3,
        activeFrames: 4,
        recoveryFrames: 6,
        totalFrames: 13,
        damage: 31,
        meterGain: 10,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 3,
            duration: 4,
            offsetX: 1.0,
            offsetY: 1.45,
            width: 0.75,
            height: 0.55,
            damage: 31,
            knockbackX: 0.1,
            knockbackY: 0.02,
            hitstun: 14,
            blockstun: 8,
            isHeavy: false,
            humorText: '2ND JAB!',
            soundType: 'light',
          },
        ],
      },
    },
    {
      id: 'moshon_combo_1_finish',
      name: 'Holon 1-2 Overhand',
      fromMoveName: 'Jab Extension',
      nextButton: 'HP',
      displayChain: 'LP ➔ LP ➔ Heavy Overhand (HP)',
      nextMove: {
        name: 'Combo Overhand Finish',
        type: 'HEAVY_PUNCH',
        startupFrames: 4,
        activeFrames: 6,
        recoveryFrames: 12,
        totalFrames: 22,
        damage: 72,
        meterGain: 15,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 4,
            duration: 6,
            offsetX: 1.25,
            offsetY: 1.4,
            width: 0.95,
            height: 0.85,
            damage: 72,
            knockbackX: 0.32,
            knockbackY: 0.08,
            hitstun: 26,
            blockstun: 14,
            isHeavy: true,
            humorText: '1-2-OVERHAND!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'moshon_combo_2_overhand',
      name: 'Stomp to Overhand',
      fromMoveName: 'Stomp Kick',
      nextButton: 'HP',
      displayChain: 'Stomp Kick (LK) ➔ Heavy Overhand (HP)',
      nextMove: {
        name: 'Stomp Overhand Link',
        type: 'HEAVY_PUNCH',
        startupFrames: 4,
        activeFrames: 6,
        recoveryFrames: 10,
        totalFrames: 20,
        damage: 62,
        meterGain: 12,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 4,
            duration: 6,
            offsetX: 1.2,
            offsetY: 1.4,
            width: 0.9,
            height: 0.8,
            damage: 62,
            knockbackX: 0.15,
            knockbackY: 0.04,
            hitstun: 20,
            blockstun: 12,
            isHeavy: true,
            humorText: 'LINK!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'moshon_combo_2_finish',
      name: 'Stomp-Overhand-Roundhouse',
      fromMoveName: 'Stomp Overhand Link',
      nextButton: 'HK',
      displayChain: 'LK ➔ HP ➔ Big Roundhouse (HK)',
      nextMove: {
        name: 'Roundhouse Knockdown',
        type: 'HEAVY_KICK',
        startupFrames: 5,
        activeFrames: 7,
        recoveryFrames: 14,
        totalFrames: 26,
        damage: 78,
        meterGain: 18,
        isHeavy: true,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 5,
            duration: 7,
            offsetX: 1.4,
            offsetY: 1.2,
            width: 1.05,
            height: 0.9,
            damage: 78,
            knockbackX: 0.45,
            knockbackY: 0.22,
            hitstun: 32,
            blockstun: 16,
            isHeavy: true,
            humorText: 'KNOCKDOWN!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'moshon_combo_3_second',
      name: 'Second Heavy Punch',
      fromMoveName: 'Heavy Overhand',
      nextButton: 'HP',
      displayChain: 'Heavy Overhand (HP) ➔ Second Heavy (HP)',
      nextMove: {
        name: 'Second Heavy Punch',
        type: 'HEAVY_PUNCH',
        startupFrames: 4,
        activeFrames: 6,
        recoveryFrames: 10,
        totalFrames: 20,
        damage: 59,
        meterGain: 14,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 4,
            duration: 6,
            offsetX: 1.2,
            offsetY: 1.4,
            width: 0.9,
            height: 0.8,
            damage: 59,
            knockbackX: 0.16,
            knockbackY: 0.04,
            hitstun: 22,
            blockstun: 12,
            isHeavy: true,
            humorText: 'DOUBLE HEAVY!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'moshon_combo_3_finish',
      name: 'Guard Breaker Strike',
      fromMoveName: 'Second Heavy Punch',
      nextButton: 'HP',
      displayChain: 'HP ➔ HP ➔ Guard Breaker (HP)',
      nextMove: {
        name: 'Guard Breaker Finish',
        type: 'HEAVY_PUNCH',
        startupFrames: 6,
        activeFrames: 8,
        recoveryFrames: 16,
        totalFrames: 30,
        damage: 88,
        meterGain: 20,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 6,
            duration: 8,
            offsetX: 1.45,
            offsetY: 1.35,
            width: 1.15,
            height: 0.95,
            damage: 88,
            knockbackX: 0.5,
            knockbackY: 0.25,
            hitstun: 38,
            blockstun: 6, // Breaks guard!
            isHeavy: true,
            humorText: 'GUARD CRUSH!!',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  supers: [
    {
      id: 'moshon_super_lvl1',
      name: 'SHORT CIRCUIT',
      level: 1,
      meterCost: 100,
      command: 'QCF',
      button: 'HP',
      commandDisplay: '↓ → + HP (Tap SUPER)',
      description: 'Level 1 Super (1 Level): Pulls two live wires from belt and jams them into the opponent! Electric sparks, cartoon x-ray skeleton flash 3x, smoking ears. "ZZZAP!"',
      move: {
        name: 'SHORT CIRCUIT',
        type: 'SUPER_MOVE',
        startupFrames: 8,
        activeFrames: 28,
        recoveryFrames: 16,
        totalFrames: 52,
        damage: 111,
        meterGain: 0,
        superCost: 100,
        isSuper: true,
        isHeavy: true,
        animType: 'short_circuit',
        hitboxes: [
          {
            startFrame: 8,
            duration: 28,
            offsetX: 1.45,
            offsetY: 1.35,
            width: 1.15,
            height: 0.95,
            damage: 111,
            knockbackX: 0.45,
            knockbackY: 0.2,
            hitstun: 30,
            blockstun: 16,
            isHeavy: true,
            humorText: 'ZZZAP!',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'moshon_super_lvl2',
      name: 'OVERCLOCKED',
      level: 2,
      meterCost: 200,
      command: 'QCB',
      button: 'HK',
      commandDisplay: '↓ ← + HK (↓ + SUPER)',
      description: 'Level 2 Super (2 Levels): Slaps a glowing computer chip onto chest! Speed x1.5, glowing blue glasses & circuit jacket for 6s. 5 hits freezes foe in "FATAL ERROR" screen for 1.5s!',
      move: {
        name: 'OVERCLOCKED',
        type: 'SUPER_MOVE',
        startupFrames: 8,
        activeFrames: 16,
        recoveryFrames: 12,
        totalFrames: 36,
        damage: 0,
        meterGain: 0,
        superCost: 200,
        isSuper: true,
        isHeavy: true,
        animType: 'overclocked',
        hitboxes: [],
      },
    },
    {
      id: 'moshon_super_lvl3',
      name: "LINOY'S RAGE! (ULTIMATE)",
      level: 3,
      meterCost: 300,
      command: 'DOWN_DOWN',
      button: 'HP',
      commandDisplay: '↓ ↓ + LP + HP (Hold SUPER 1s)',
      description: 'Level 3 Ultimate (3 Levels): Phone rings with "LINOY CALLING..." -> "WHERE ARE YOU?!". Trembles in fear, gold chain snaps, turns red with ear steam & electric fists! Furious punch flurry + fiery blast (~45% dmg). Ends with answering "Yes my love, coming home now!" and running out/in.',
      move: {
        name: "LINOY'S RAGE!",
        type: 'SUPER_MOVE',
        startupFrames: 14,
        activeFrames: 32,
        recoveryFrames: 22,
        totalFrames: 68,
        damage: 299,
        meterGain: 0,
        superCost: 300,
        isSuper: true,
        isHeavy: true,
        animType: 'linoy_rage',
        hitboxes: [
          {
            startFrame: 14,
            duration: 32,
            offsetX: 1.85,
            offsetY: 1.3,
            width: 1.7,
            height: 1.3,
            damage: 299,
            knockbackX: 0.75,
            knockbackY: 0.45,
            hitstun: 50,
            blockstun: 25,
            isHeavy: true,
            humorText: "LINOY'S RAGE!!!",
            soundType: 'super',
          },
        ],
      },
    },
  ],
  superSpecial: {
    id: 'moshon_super_lvl3',
    name: "LINOY'S RAGE! (ULTIMATE)",
    command: 'DOWN_DOWN',
    button: 'HP',
    commandDisplay: '↓↓ + LP+HP (Hold SUPER 1s)',
    description: 'Level 3 Ultimate (3 Levels): Phone rings with "LINOY CALLING..." -> "WHERE ARE YOU?!". Trembles in fear, gold chain snaps, turns red with ear steam & electric fists! Exploding flurry + fiery blast (~45% dmg).',
    move: {
      name: "LINOY'S RAGE!",
      type: 'SUPER_MOVE',
      startupFrames: 14,
      activeFrames: 32,
      recoveryFrames: 22,
      totalFrames: 68,
      damage: 299,
      meterGain: 0,
      superCost: 300,
      isSuper: true,
      isHeavy: true,
      animType: 'linoy_rage',
      hitboxes: [
        {
          startFrame: 14,
          duration: 32,
          offsetX: 1.85,
          offsetY: 1.3,
          width: 1.7,
          height: 1.3,
          damage: 299,
          knockbackX: 0.75,
          knockbackY: 0.45,
          hitstun: 50,
          blockstun: 25,
          isHeavy: true,
          humorText: "LINOY'S RAGE!!!",
          soundType: 'super',
        },
      ],
    },
  },
};

export const FIGHTER_MATTHEW: FighterConfig = {
  id: 'fighter_matthew',
  name: 'Matthew',
  subtitle: 'The Terrifying',
  stats: {
    maxHealth: 1250, // Health 125 (Tank archetype)
    walkSpeed: 0.065, // Speed 4/10 (slow, heavy)
    dashSpeed: 0.14,
    jumpForce: 0.24, // Jump 3/10
    powerMultiplier: 1.25, // Power 9/10 (heavy hitting)
    weight: 1.35, // Hard to knock down
  },
  appearance: {
    primaryColor: 0x1e293b, // Dark jeans
    secondaryColor: 0x09090b, // Plain black v-neck
    skinColor: 0xb07850, // Warm brown (#B07850)
    gloveColor: 0xb07850, // Bare hands
    hairColor: 0x1a120b, // Dark stubble & thick eyebrows
    eyeColor: 0x2e1808, // Dark brown eyes
    bodyType: 'heavy', // Chubby, round belly, thick arms, short neck
    headShape: 'round', // Completely bald, shiny specular highlight, round full face, round cheeks
    eyebrows: 'thick', // Thick dark eyebrows
    mouth: 'grin', // Very big wide smile with big white teeth
    noseShape: 'broad',
    noseSize: 'medium',
    hairStyle: 'bald',
    beard: 'stubble', // Short dark stubble along jawline and chin
    shirtType: 'tshirt', // Plain black v-neck t-shirt
    shirtColor: 0x09090b,
    pantsType: 'long_pants', // Dark jeans
    pantsColor: 0x1e293b,
    shoesType: 'sneakers', // Sneakers
    shoesColor: 0xf8fafc,
    gloveType: 'bare_hands',
    accessory: 'none',
  },
  victoryQuote: 'Calculated! Now where did I put my shawarma?',
  defeatQuote: 'Finally, a nap...',
  koAnimation: {
    type: 'matthew_timber',
    quote: 'Finally, a nap...',
  },
  moves: {
    LIGHT_PUNCH: {
      name: 'Heavy Jab',
      type: 'LIGHT_PUNCH',
      startupFrames: 7,
      activeFrames: 5,
      recoveryFrames: 9,
      totalFrames: 21,
      damage: 38,
      meterGain: 10,
      animType: 'lp',
      hitboxes: [
        {
          startFrame: 7,
          duration: 5,
          offsetX: 1.0,
          offsetY: 1.35,
          width: 0.75,
          height: 0.6,
          damage: 38,
          knockbackX: 0.12,
          knockbackY: 0.03,
          hitstun: 16,
          blockstun: 9,
          isHeavy: false,
          humorText: 'THUD!',
          soundType: 'light',
        },
      ],
    },
    HEAVY_PUNCH: {
      name: 'Double Hammer Smash',
      type: 'HEAVY_PUNCH',
      startupFrames: 14,
      activeFrames: 7,
      recoveryFrames: 18,
      totalFrames: 39,
      damage: 105,
      meterGain: 22,
      isHeavy: true,
      animType: 'hp',
      hitboxes: [
        {
          startFrame: 14,
          duration: 7,
          offsetX: 1.15,
          offsetY: 1.25,
          width: 1.05,
          height: 1.0,
          damage: 105,
          knockbackX: 0.36,
          knockbackY: 0.22,
          hitstun: 28,
          blockstun: 16,
          isHeavy: true,
          humorText: 'CRUSH!',
          soundType: 'heavy',
        },
      ],
    },
    LIGHT_KICK: {
      name: 'Heavy Stomp',
      type: 'LIGHT_KICK',
      startupFrames: 8,
      activeFrames: 6,
      recoveryFrames: 10,
      totalFrames: 24,
      damage: 42,
      meterGain: 11,
      animType: 'lk',
      attackLevel: 'low',
      hitboxes: [
        {
          startFrame: 8,
          duration: 6,
          offsetX: 0.9,
          offsetY: 0.35,
          width: 0.8,
          height: 0.55,
          damage: 42,
          knockbackX: 0.14,
          knockbackY: 0.05,
          hitstun: 18,
          blockstun: 10,
          isHeavy: false,
          humorText: 'STOMP!',
          soundType: 'light',
          attackLevel: 'low',
        },
      ],
    },
    HEAVY_KICK: {
      name: 'Belly Bump',
      type: 'HEAVY_KICK',
      startupFrames: 12,
      activeFrames: 8,
      recoveryFrames: 15,
      totalFrames: 35,
      damage: 92,
      meterGain: 20,
      isHeavy: true,
      animType: 'hk',
      hitboxes: [
        {
          startFrame: 12,
          duration: 8,
          offsetX: 1.05,
          offsetY: 1.05,
          width: 1.1,
          height: 0.9,
          damage: 92,
          knockbackX: 0.45,
          knockbackY: 0.12,
          hitstun: 26,
          blockstun: 18,
          isHeavy: true,
          humorText: 'BOING!',
          soundType: 'heavy',
        },
      ],
    },
    SUPER_MOVE: {
      name: 'DO THE MATH',
      type: 'SUPER_MOVE',
      startupFrames: 8,
      activeFrames: 32,
      recoveryFrames: 18,
      totalFrames: 58,
      damage: 165,
      meterGain: 0,
      isSuper: true,
      superCost: 100,
      animType: 'do_the_math',
      hitboxes: [
        {
          startFrame: 8,
          duration: 32,
          offsetX: 1.25,
          offsetY: 1.35,
          width: 1.2,
          height: 1.0,
          damage: 165,
          knockbackX: 0.55,
          knockbackY: 0.28,
          hitstun: 45,
          blockstun: 22,
          isHeavy: true,
          humorText: 'CALCULATED!',
          soundType: 'super',
        },
      ],
    },
  },
  specials: [
    {
      id: 'matthew_special_belly_bounce',
      name: 'Belly Bounce',
      command: 'DOUBLE_TAP_F',
      button: 'HP',
      commandDisplay: '→ → + HP',
      description: 'Charges belly-first. Opponent bounces off his belly across the ring!',
      move: {
        name: 'Belly Bounce',
        type: 'HEAVY_PUNCH',
        startupFrames: 8,
        activeFrames: 14,
        recoveryFrames: 14,
        totalFrames: 36,
        damage: 88,
        meterGain: 18,
        isHeavy: true,
        animType: 'belly_bounce',
        hitboxes: [
          {
            startFrame: 8,
            duration: 14,
            offsetX: 1.2,
            offsetY: 1.05,
            width: 1.15,
            height: 0.95,
            damage: 88,
            knockbackX: 0.65,
            knockbackY: 0.28,
            hitstun: 32,
            blockstun: 16,
            isHeavy: true,
            humorText: 'BOUNCE!!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'matthew_special_door_shield',
      name: 'Door Shield',
      command: 'QCB',
      button: 'LP',
      commandDisplay: '↓ ← + LP',
      description: 'Holds up a solid wooden door as a shield for 1 sec. Blocks everything & reflects projectiles!',
      move: {
        name: 'Door Shield',
        type: 'LIGHT_PUNCH',
        startupFrames: 3,
        activeFrames: 60,
        recoveryFrames: 10,
        totalFrames: 73,
        damage: 0,
        meterGain: 15,
        animType: 'door_shield',
        hitboxes: [],
      },
    },
    {
      id: 'matthew_special_snack_break',
      name: 'Snack Break',
      command: 'DOWN_DOWN',
      button: 'LP',
      commandDisplay: '↓ ↓ + LP',
      description: 'Pulls out a warm pita and takes a snack, recovering 5% health (can be interrupted if hit).',
      move: {
        name: 'Snack Break',
        type: 'LIGHT_PUNCH',
        startupFrames: 12,
        activeFrames: 30,
        recoveryFrames: 12,
        totalFrames: 54,
        damage: 0,
        meterGain: 12,
        animType: 'snack_break',
        hitboxes: [],
      },
    },
    {
      id: 'matthew_special_snore_wave',
      name: 'Snore Wave',
      command: 'QCF',
      button: 'HK',
      commandDisplay: '↓ → + HK',
      description: 'Falls asleep standing for a moment; a giant snore shockwave of "Zzz" letters flies forward!',
      move: {
        name: 'Snore Wave',
        type: 'HEAVY_KICK',
        startupFrames: 12,
        activeFrames: 12,
        recoveryFrames: 16,
        totalFrames: 40,
        damage: 65,
        meterGain: 16,
        animType: 'snore_wave',
        hitboxes: [
          {
            startFrame: 12,
            duration: 10,
            offsetX: 1.1,
            offsetY: 1.35,
            width: 0.9,
            height: 0.8,
            damage: 65,
            knockbackX: 0.38,
            knockbackY: 0.14,
            hitstun: 24,
            blockstun: 14,
            isHeavy: false,
            humorText: 'Zzz...',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: 'matthew_combo_1',
      name: 'Jab Jab Hammer',
      fromMoveName: 'Heavy Jab',
      nextButton: 'LP',
      displayChain: 'LP → LP → HP',
      nextMove: {
        name: 'Heavy Jab 2',
        type: 'LIGHT_PUNCH',
        startupFrames: 5,
        activeFrames: 5,
        recoveryFrames: 8,
        totalFrames: 18,
        damage: 42,
        meterGain: 10,
        animType: 'lp',
        hitboxes: [
          {
            startFrame: 5,
            duration: 5,
            offsetX: 1.0,
            offsetY: 1.35,
            width: 0.75,
            height: 0.6,
            damage: 42,
            knockbackX: 0.14,
            knockbackY: 0.04,
            hitstun: 18,
            blockstun: 10,
            isHeavy: false,
            humorText: 'BOP!',
            soundType: 'light',
          },
        ],
      },
    },
    {
      id: 'matthew_combo_1_finish',
      name: 'Jab Jab Hammer Finish',
      fromMoveName: 'Heavy Jab 2',
      nextButton: 'HP',
      displayChain: 'LP → LP → HP',
      nextMove: {
        name: 'Hammer Finisher',
        type: 'HEAVY_PUNCH',
        startupFrames: 10,
        activeFrames: 6,
        recoveryFrames: 16,
        totalFrames: 32,
        damage: 98,
        meterGain: 18,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 10,
            duration: 6,
            offsetX: 1.15,
            offsetY: 1.25,
            width: 1.0,
            height: 0.9,
            damage: 98,
            knockbackX: 0.42,
            knockbackY: 0.20,
            hitstun: 28,
            blockstun: 15,
            isHeavy: true,
            humorText: 'SMASH!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'matthew_combo_2_bump',
      name: 'Stomp Belly Hammer Step 2',
      fromMoveName: 'Heavy Stomp',
      nextButton: 'HK',
      displayChain: 'LK → HK → HP',
      nextMove: {
        name: 'Belly Bump Link',
        type: 'HEAVY_KICK',
        startupFrames: 8,
        activeFrames: 6,
        recoveryFrames: 12,
        totalFrames: 26,
        damage: 55,
        meterGain: 14,
        animType: 'hk',
        hitboxes: [
          {
            startFrame: 8,
            duration: 6,
            offsetX: 1.0,
            offsetY: 1.05,
            width: 0.95,
            height: 0.85,
            damage: 55,
            knockbackX: 0.28,
            knockbackY: 0.08,
            hitstun: 22,
            blockstun: 12,
            isHeavy: true,
            humorText: 'BUMP!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'matthew_combo_2_finish',
      name: 'Stomp Belly Hammer Knockdown',
      fromMoveName: 'Belly Bump Link',
      nextButton: 'HP',
      displayChain: 'LK → HK → HP',
      nextMove: {
        name: 'Knockdown Hammer',
        type: 'HEAVY_PUNCH',
        startupFrames: 10,
        activeFrames: 7,
        recoveryFrames: 16,
        totalFrames: 33,
        damage: 108,
        meterGain: 20,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 10,
            duration: 7,
            offsetX: 1.2,
            offsetY: 1.2,
            width: 1.1,
            height: 0.95,
            damage: 108,
            knockbackX: 0.55,
            knockbackY: 0.32,
            hitstun: 36,
            blockstun: 18,
            isHeavy: true,
            humorText: 'KNOCKDOWN!',
            soundType: 'heavy',
          },
        ],
      },
    },
    {
      id: 'matthew_combo_3_guardbreak',
      name: 'Double Hammer Guard Break',
      fromMoveName: 'Double Hammer Smash',
      nextButton: 'HP',
      displayChain: 'HP → HP (Guard Break)',
      nextMove: {
        name: 'Guard Break Hammer',
        type: 'HEAVY_PUNCH',
        startupFrames: 12,
        activeFrames: 8,
        recoveryFrames: 18,
        totalFrames: 38,
        damage: 115,
        meterGain: 24,
        isHeavy: true,
        animType: 'hp',
        hitboxes: [
          {
            startFrame: 12,
            duration: 8,
            offsetX: 1.2,
            offsetY: 1.25,
            width: 1.1,
            height: 1.0,
            damage: 115,
            knockbackX: 0.6,
            knockbackY: 0.28,
            hitstun: 38,
            blockstun: 0, // Breaks guard cleanly!
            isHeavy: true,
            humorText: 'GUARD CRUSH!!',
            soundType: 'heavy',
          },
        ],
      },
    },
  ],
  supers: [
    {
      id: 'matthew_super_lvl1',
      level: 1,
      meterCost: 100,
      name: 'DO THE MATH',
      command: 'QCF',
      button: 'HP',
      commandDisplay: '↓ → + HP (Tap S1)',
      description: 'Level 1 (1 Level): Time freezes and floating math formulas calculate the trajectory for a 7-punch calculated combo (25% total damage)!',
      move: {
        name: 'DO THE MATH',
        type: 'SUPER_MOVE',
        startupFrames: 8,
        activeFrames: 34,
        recoveryFrames: 18,
        totalFrames: 60,
        damage: 250,
        meterGain: 0,
        isSuper: true,
        superCost: 100,
        animType: 'do_the_math',
        hitboxes: [
          { startFrame: 8, duration: 4, offsetX: 1.15, offsetY: 1.35, width: 1.1, height: 0.9, damage: 35, knockbackX: 0.05, knockbackY: 0.0, hitstun: 25, blockstun: 15, isHeavy: false, humorText: '1 (∠=45°)', soundType: 'super' },
          { startFrame: 12, duration: 4, offsetX: 1.2, offsetY: 1.45, width: 1.1, height: 0.9, damage: 35, knockbackX: 0.05, knockbackY: 0.0, hitstun: 25, blockstun: 15, isHeavy: false, humorText: '2 (π)', soundType: 'super' },
          { startFrame: 16, duration: 4, offsetX: 1.25, offsetY: 1.30, width: 1.1, height: 0.9, damage: 35, knockbackX: 0.05, knockbackY: 0.0, hitstun: 25, blockstun: 15, isHeavy: false, humorText: '3 (a²+b²)', soundType: 'super' },
          { startFrame: 20, duration: 4, offsetX: 1.3, offsetY: 1.40, width: 1.1, height: 0.9, damage: 35, knockbackX: 0.05, knockbackY: 0.0, hitstun: 25, blockstun: 15, isHeavy: false, humorText: '4 (√x)', soundType: 'super' },
          { startFrame: 24, duration: 4, offsetX: 1.35, offsetY: 1.35, width: 1.1, height: 0.9, damage: 35, knockbackX: 0.05, knockbackY: 0.0, hitstun: 25, blockstun: 15, isHeavy: false, humorText: '5 (E=mc²)', soundType: 'super' },
          { startFrame: 28, duration: 4, offsetX: 1.4, offsetY: 1.45, width: 1.1, height: 0.9, damage: 35, knockbackX: 0.05, knockbackY: 0.0, hitstun: 25, blockstun: 15, isHeavy: false, humorText: '6 (∫dx)', soundType: 'super' },
          { startFrame: 32, duration: 6, offsetX: 1.45, offsetY: 1.35, width: 1.2, height: 1.0, damage: 40, knockbackX: 0.65, knockbackY: 0.35, hitstun: 50, blockstun: 25, isHeavy: true, humorText: '= K.O.! CALCULATED!', soundType: 'super' },
        ],
      },
    },
    {
      id: 'matthew_super_lvl2',
      level: 2,
      meterCost: 200,
      name: 'DOOR-TO-DOOR SALES',
      command: 'QCB',
      button: 'HK',
      commandDisplay: '↓ ← + HK (Tap S2)',
      description: 'Level 2 (2 Levels, 4s max): 0.3s startup hitbox. Slams opponent through wooden & steel doors, then squashes with an armored door with Lifetime Warranty (35% damage)!',
      move: {
        name: 'DOOR-TO-DOOR SALES',
        type: 'SUPER_MOVE',
        startupFrames: 18, // 0.3 sec startup at 60fps
        activeFrames: 6,
        recoveryFrames: 216,
        totalFrames: 240, // 4.0 sec max duration
        damage: 350, // 35% damage applied once at final hit
        meterGain: 0,
        isSuper: true,
        superCost: 200,
        animType: 'door_to_door',
        hitboxes: [
          // Startup capture hitbox: connects after 0.3s startup to lock opponent into cinematic
          {
            startFrame: 18,
            duration: 6,
            offsetX: 1.25,
            offsetY: 1.25,
            width: 1.35,
            height: 1.1,
            damage: 0, // Damage is applied once at the final hit
            knockbackX: 0,
            knockbackY: 0,
            hitstun: 240,
            blockstun: 0,
            isHeavy: true,
            humorText: 'DOORBELL! 🔔',
            soundType: 'super',
          },
        ],
      },
    },
    {
      id: 'matthew_super_lvl3',
      level: 3,
      meterCost: 300,
      name: 'THE SLEEPING GIANT (ULTIMATE)',
      command: 'DOWN_DOWN',
      button: 'HP',
      commandDisplay: '↓ ↓ + LP + HP (Tap S3)',
      description: 'Level 3 Ultimate (3 Levels, 5s max): 0.3s startup hitbox. Falls asleep, floating shawarma appears, grows 3x bigger, belly-flops creating crater for 45% damage!',
      move: {
        name: 'THE SLEEPING GIANT (ULTIMATE)',
        type: 'SUPER_MOVE',
        startupFrames: 18, // 0.3 sec startup at 60fps
        activeFrames: 6,
        recoveryFrames: 276,
        totalFrames: 300, // 5.0 sec max duration
        damage: 450, // 45% damage applied once at final hit
        meterGain: 0,
        isSuper: true,
        superCost: 300,
        animType: 'sleeping_giant',
        hitboxes: [
          // Startup capture hitbox: connects after 0.3s startup to lock opponent into cinematic
          {
            startFrame: 18,
            duration: 6,
            offsetX: 1.30,
            offsetY: 1.25,
            width: 1.40,
            height: 1.1,
            damage: 0, // Damage is applied once at the final hit
            knockbackX: 0,
            knockbackY: 0,
            hitstun: 300,
            blockstun: 0,
            isHeavy: true,
            humorText: 'SLEEPING GIANT!',
            soundType: 'super',
          },
        ],
      },
    },
  ],
  superSpecial: {
    id: 'matthew_super_lvl3',
    name: 'THE SLEEPING GIANT (ULTIMATE)',
    command: 'DOWN_DOWN',
    button: 'HP',
    commandDisplay: '↓↓ + LP+HP (Tap S3)',
    description: 'Level 3 Ultimate (3 Levels, 5s max): 0.3s startup hitbox. Falls asleep, floating shawarma appears, grows 3x bigger, belly-flops creating crater for 45% damage!',
    move: {
      name: 'THE SLEEPING GIANT (ULTIMATE)',
      type: 'SUPER_MOVE',
      startupFrames: 18,
      activeFrames: 6,
      recoveryFrames: 276,
      totalFrames: 300,
      damage: 450,
      meterGain: 0,
      isSuper: true,
      superCost: 300,
      animType: 'sleeping_giant',
      hitboxes: [
        {
          startFrame: 18,
          duration: 6,
          offsetX: 1.30,
          offsetY: 1.25,
          width: 1.40,
          height: 1.1,
          damage: 0,
          knockbackX: 0,
          knockbackY: 0,
          hitstun: 300,
          blockstun: 0,
          isHeavy: true,
          humorText: 'SLEEPING GIANT!',
          soundType: 'super',
        },
      ],
    },
  },
};

export const AVAILABLE_FIGHTERS: FighterConfig[] = [
  FIGHTER_MATTHEW, // Matthew "The Terrifying"
  FIGHTER_DANDAN, // Set as Player 1 for testing
  FIGHTER_MOSHON, // Moshon "The Eliminator from Holon"
  FIGHTER_BOB,
  FIGHTER_KYLE,
];

export function createInitialFighterState(
  config: FighterConfig,
  playerIndex: 1 | 2,
  startX?: number
): FighterState {
  const defaultX = playerIndex === 1 ? -2.8 : 2.8;
  return {
    id: `${config.id}_p${playerIndex}`,
    playerIndex,
    config,
    x: startX !== undefined ? startX : defaultX,
    y: 0,
    z: 0,
    vx: 0,
    vy: 0,
    facing: playerIndex === 1 ? 1 : -1,
    health: config.stats.maxHealth,
    maxHealth: config.stats.maxHealth,
    displayHealth: config.stats.maxHealth,
    superMeter: 0,
    maxSuperMeter: 300, // 3 levels for every fighter (100 per level)
    actionState: 'IDLE',
    currentMove: null,
    moveFrame: 0,
    hitstunFrames: 0,
    blockstunFrames: 0,
    isBlocking: false,
    isCrouching: false,
    isGrounded: true,
    hasHitThisMove: false,
    hasShownPopUpThisMove: false,
    comboCount: 0,
    roundsWon: 0,
    eyePop: 0,
    wobbleAngle: 0,
    koTumble: 0,
    isKo: false,
    slowDebuffTicks: 0,
    counterStanceTicks: 0,
    glassesGlintBuff: false,
    earRadarTicks: 0,
    superMeterHoldTicks: 0,
  };
}
